-- Primary key creating Triggers

CREATE TRIGGER pk_uni
BEFORE INSERT ON UNIVERSE
FOR EACH ROW
EXECUTE PROCEDURE pk_func_uni();

CREATE TRIGGER pk_item
BEFORE INSERT ON ITEM
FOR EACH ROW
EXECUTE PROCEDURE pk_func_item();

CREATE TRIGGER pk_player
BEFORE INSERT ON PLAYER
FOR EACH ROW
EXECUTE PROCEDURE pk_func_player();

CREATE TRIGGER pk_gm
BEFORE INSERT ON GAMEMODE
FOR EACH ROW
EXECUTE PROCEDURE pk_func_gm();

CREATE TRIGGER pk_word
BEFORE INSERT ON WORD
FOR EACH ROW
EXECUTE PROCEDURE pk_func_word();

CREATE TRIGGER pk_un_wr
BEFORE INSERT ON UN_WR
FOR EACH ROW
EXECUTE PROCEDURE pk_func_un_wr();

CREATE TRIGGER pk_precip
BEFORE INSERT ON PRECIPITATION
FOR EACH ROW
EXECUTE PROCEDURE pk_func_precip();

CREATE TRIGGER pk_tool
BEFORE INSERT ON TOOL
FOR EACH ROW
EXECUTE PROCEDURE pk_func_tool();

CREATE TRIGGER pk_block
BEFORE INSERT ON BLOCK
FOR EACH ROW
EXECUTE PROCEDURE pk_func_block();

CREATE TRIGGER pk_biome
BEFORE INSERT ON BIOME
FOR EACH ROW
EXECUTE PROCEDURE pk_func_biome();

CREATE TRIGGER pk_wr_bi
BEFORE INSERT ON WR_BI
FOR EACH ROW
EXECUTE PROCEDURE pk_func_wr_bi();

CREATE TRIGGER pk_weapon
BEFORE INSERT ON WEAPON
FOR EACH ROW
EXECUTE PROCEDURE pk_func_weapon();

CREATE TRIGGER pk_plant
BEFORE INSERT ON PLANT
FOR EACH ROW
EXECUTE PROCEDURE pk_func_plant();

CREATE TRIGGER pk_effect
BEFORE INSERT ON EFFECT
FOR EACH ROW
EXECUTE PROCEDURE pk_func_effect();

CREATE TRIGGER pk_food
BEFORE INSERT ON FOOD
FOR EACH ROW
EXECUTE PROCEDURE pk_func_food();

CREATE TRIGGER pk_drop
BEFORE INSERT ON DROPS
FOR EACH ROW
EXECUTE PROCEDURE pk_func_drop();

CREATE TRIGGER pk_dmg_type
BEFORE INSERT ON DMG_TYPE
FOR EACH ROW
EXECUTE PROCEDURE pk_func_dmg_type();

CREATE TRIGGER pk_friendm
BEFORE INSERT ON FRIENDMODE
FOR EACH ROW
EXECUTE PROCEDURE pk_func_friendm();

CREATE TRIGGER pk_mob
BEFORE INSERT ON MOB
FOR EACH ROW
EXECUTE PROCEDURE pk_func_mob();

CREATE TRIGGER pk_bi_mob
BEFORE INSERT ON BI_MOB
FOR EACH ROW
EXECUTE PROCEDURE pk_func_bi_mob();

CREATE TRIGGER pk_inv
BEFORE INSERT ON INVENTORY
FOR EACH ROW
EXECUTE PROCEDURE pk_func_inv();

CREATE TRIGGER pk_mat
BEFORE INSERT ON MATERIAL
FOR EACH ROW
EXECUTE PROCEDURE pk_func_mat();
